### ISSUE TITLE
Problems with the new metin update

### ISSUE THREAD

**Issue by myalterme** [MetinOpenBot/OpenBot#14]
Hi,
after yesterday's metin update I had problems of crashing and also when not crashing the bot to automatically attack did not work.

**Comment by Celuni** [comment]
This is because OpenBot is not actually **open source**, thus we can't update the offsets after a patch.
The last release was protected with **Themida**, the one before that not!
Don't let someone fool you by making it look like a repo with good intentions, they also now **deleted all releases**.
**Do not trust binaries from randoms.**

**Comment by eXploit-metin** [comment]
Let me clear something here, OpenBot is open source. In contrast to that, eXLib is not open source, the reason for is a possible premium version which is still unclear if it will ever com out.
If you don't wanna trust it is fine for us, just don't use it :)

**Comment by eXploit-metin** [comment]
Related to the original question, tonight there will be an update to fix som issues.
